import { test, assert, equal } from "./test-runner.js";
import { obtenerContenido } from "../content/content-provider.js";
import { TIMELINE_DATA } from "../data/timeline-data.js";
import { NIVELES_ALERTA } from "../data/constants.js";
import { crearFaqSchema } from "../utils/schema-builders.js";
import { renderFaq } from "../renderers/faq-renderer.js";
import { crearTimelineRenderer } from "../renderers/timeline-renderer.js";
import { crearAlertsRenderer } from "../renderers/alerts-renderer.js";
import { instalarFakeDom, FakeNode } from "./fake-dom.js";
import { babyFeedingEngine } from "../engines/baby-feeding-engine.js";
import { entrada } from "./fixtures.js";
instalarFakeDom();
const contenido=obtenerContenido();
test("existen exactamente 20 FAQ",()=>equal(contenido.faq.length,20));
test("FAQ tienen IDs únicos",()=>equal(new Set(contenido.faq.map((x)=>x.id)).size,20));
test("FAQ no tienen campos vacíos",()=>assert(contenido.faq.every((x)=>x.pregunta&&x.respuesta)));
test("FAQ Schema conserva orden y preguntas",()=>{const s=crearFaqSchema(contenido.faq);equal(s.mainEntity.length,20);equal(JSON.stringify(s.mainEntity.map((x)=>x.name)),JSON.stringify(contenido.faq.map((x)=>x.pregunta)));});
test("FAQ Schema conserva respuestas exactas",()=>{const s=crearFaqSchema(contenido.faq);equal(JSON.stringify(s.mainEntity.map((x)=>x.acceptedAnswer.text)),JSON.stringify(contenido.faq.map((x)=>x.respuesta)));});
test("FAQ visible consume las 20 entradas",()=>equal(renderFaq(contenido.faq,new FakeNode("div")),20));
test("timeline editorial tiene siete etapas",()=>equal(contenido.timelineCompleto.length,7));
test("timeline editorial cubre todas las claves de data",()=>{const claves=new Set(contenido.timelineCompleto.map((x)=>x.etapa));assert(TIMELINE_DATA.every((x)=>claves.has(x.etapa)));});
test("timeline destaca etapa calculada",()=>{const d=new FakeNode("section");crearTimelineRenderer(d)(babyFeedingEngine(entrada()));assert(d.children.length===3);});
test("catálogo de alertas cubre todos los niveles",()=>assert(Object.values(NIVELES_ALERTA).every((nivel)=>contenido.alertas[nivel])));
test("render de alertas acepta nivel consultar",()=>{const d=new FakeNode("article");crearAlertsRenderer(d)(babyFeedingEngine(entrada({nacimiento:"prematuro"})));assert(d.children.length>0);});
test("todas las fuentes usan HTTPS",()=>assert(contenido.fuentes.every((x)=>new URL(x.url).protocol==="https:")));
test("todas las relacionadas usan HTTPS",()=>assert(contenido.relacionadas.every((x)=>new URL(x.url).protocol==="https:")));
test("revisión científica tiene fecha ISO",()=>assert(/^\d{4}-\d{2}-\d{2}$/.test(contenido.revision.fechaISO)));
test("contenido de confianza está completo",()=>assert(contenido.confianza.puntos.length>=5&&contenido.confianza.revision));
test("privacidad describe el historial local sin contradicciones",()=>{const privacidad=contenido.faq.find((x)=>x.id==="privacidad")?.respuesta??"";const confianza=contenido.confianza.puntos.find((x)=>x.startsWith("Privacidad:"))??"";assert(/historial/i.test(privacidad)&&/almacenamiento local/i.test(privacidad)&&/almacenamiento local/i.test(confianza));assert(!/no existe historial|no guarda los datos/i.test(`${privacidad} ${confianza}`));});
